config/routes.rb
Rails.application.routes.draw do
  resources :appointments do
    get :today, on: :collection, as: :today
    delete :delete_all, on: :collection, as: :delete_all
    put :schedule, on: :member, as: :schedule
  end

  put :push_tomorrow, to: "appointments#push_tomorrow", as: :push_tomorrow
  delete :cancel_today, to: "appointments#cancel_today", as: :cancel_today
  root 'appointments#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy, :schedule]

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    redirect_to @appointment, notice: "Appointment saved"
  end

  def update
    redirect_to @appointment, notice: "Appointment updated"
  end

  def destroy
    redirect_to appointments_path, notice: "Appointment deleted"
  end

  def today
  end

  def schedule
    redirect_to @appointment, notice: "Appointment rescheduled"
  end

  def push_tomorrow
    redirect_to today_appointments_path, notice: "All appointments for today pushed"
  end

  def cancel_today
    redirect_to today_appointments_path, notice: "All appointments for today cancelled"
  end

  def delete_all
    redirect_to appointments_path, notice: "All appointments cancelled"
  end

  private
    def set_appointment
      @appointment = Appointment.first
    end

    def appointment_params
      params.require(:appointment).permit(:client, :date, :time_start, :time_end, :service)
    end

    def schedule_params
      schedule_parameters = params.require(:appointment).permit(date: [:day, :month, :year], time_start: [:hour, :minute], time_end: [:hour, :minute])
      date = Date.new(
        schedule_parameters[:date][:year].to_i,
        schedule_parameters[:date][:month].to_i,
        schedule_parameters[:date][:day].to_i
      )
      time_start = Time.local(
        2000, 1, 1,
        schedule_parameters[:time_start][:hour].to_i+1,
        schedule_parameters[:time_start][:minute]
      )
      time_end = Time.local(
        2000, 1, 1,
        schedule_parameters[:time_end][:hour].to_i+1,
        schedule_parameters[:time_end][:minute].to_i
      )
      {date: date, time_start: time_start, time_end: time_end}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when "notice" then "alert alert-info"
        when "success" then "alert alert-success"
        when "error" then "alert alert-danger"
    end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.haml
= link_to appointment, class: "list-group-item list-group-item-action" do
  - if appointment.date != Date.today
    %strong="#{appointment.date} "
  %strong="#{appointment.time_start.strftime("%H:%M")} "
  = appointment.client

app/views/appointments/_appointment_details.html.haml
%h1.text-center.mb-4.mt-4 Appointment details

.row
  .col-12.col-md-5.offset-md-1
    %table.table.mt-4
      %tbody
        %tr
          %th{scope: "row"} Client
          %td=appointment.client
        %tr
          %th{scope: "row"} Date
          %td=appointment.date
        %tr
          %th{scope: "row"} Time start
          %td=appointment.time_start.strftime("%H:%M")
        %tr
          %th{scope: "row"} Time end
          %td=appointment.time_end.strftime("%H:%M")
        %tr
          %th{scope: "row"} Service
          %td=appointment.service
    .text-center
      = link_to 'Edit', edit_appointment_path(appointment), class: "btn btn-warning"
      = link_to 'Delete', appointment, method: "delete", class: "btn btn-danger", data: {confirm: "Are you sure?"}
      = link_to 'Back', appointments_path, class: "btn btn-primary"
  .col-12.col-md-5
    = render partial: 'reschedule', locals: {appointment: appointment}

app/views/appointments/_form.html.haml
.row
  .col-12.col-md-6.offset-md-3
    = form_for @appointment do |f|
      .form-group
        = f.text_field :client, class: "form-control", placeholder: :client
      .form-group
        = f.text_field :service, class: "form-control", placeholder: :service
      .form-group
        = f.label :date
        = f.date_select :date, class: "form-control", placeholder: :date
      .form-group
        = f.label :time_start
        = f.time_select :time_start, class: "form-control"
      .form-group
        = f.label :time_end
        = f.time_select :time_end, class: "form-control"

      = f.submit 'Save', class: "btn btn-primary"
      = link_to 'Back', appointments_path, class: "btn btn-danger"

app/views/appointments/_reschedule.html.haml
.card
  .card-header Reschedule
  .card-body
    = form_tag schedule_appointment_path(appointment), method: "put" do
      .form-group
        = label_tag "Date"
        = select_date appointment.date, prefix: "appointment[date]"
      .form-group
        = label_tag "Time start"
        = select_time appointment.time_start, prefix: "appointment[time_start]"
      .form-group
        = label_tag "Time end"
        = select_time appointment.time_end, prefix: "appointment[time_end]"
      = submit_tag "Change", class: "btn btn-primary"

app/views/appointments/edit.html.haml
%h1 Editing appointment

= render 'form'

app/views/appointments/index.html.haml
%h1.text-center.mb-4.mt-4 Appointments

- if @appointments.blank?
  .alert.alert-info There are no appointments
- else
  .row
    .col-12.col-md-6.offset-md-3
      .card
        .card-header
          %ul.nav.nav-pills
            %li.nav-item
              %span.nav-link.active All appointments
            %li.nav-item
              = link_to "Today", today_appointments_path, class: "nav-link"
        .card-body
          .mb-4
            = link_to "Delete all", delete_all_appointments_path, class: "btn btn-danger", method: "delete", data: {confirm: "Are you sure?"}
          .list-group
            = render @appointments

app/views/appointments/new.html.haml
%h1.text-center.mb-4.mt-4 New appointment

= render 'form'

app/views/appointments/show.html.haml
= render partial: 'appointment_details', locals: {appointment: @appointment}

app/views/appointments/today.html.haml
%h1.text-center.mb-4.mt-4 Appointments

.row
  .col-12.col-md-6.offset-md-3
    .card
      .card-header
        %ul.nav.nav-pills
          %li.nav-item
            = link_to "All appointments", appointments_path, class: "nav-link"
          %li.nav-item
            %span.nav-link.active Today
      .card-body
        -if @appointments.blank?
          .alert.alert-info No appointments today
        -else
          %p Are you sick today?
          .mb-4
            = link_to "Push to tomorrow", push_tomorrow_path, class: "btn btn-warning", method: "put"
            = link_to "Cancel all", cancel_today_path, class: "btn btn-danger", method: "delete", data: {confirm: "Are you sure?"}
          .list-group
            = render @appointments

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value|
  %p{class: flash_class(key), role: "alert"}
    = value

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand.navbar-light.bg-light
  = link_to 'Appointments', root_path, class: 'navbar-brand'
  %button.navbar-toggler{type: "button", "data-toggle": "collapse", "data-target": "#navbarNav", "aria-controls": "navbarNav", "aria-expanded": "false", "aria-label": "Toggle navigation"}
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarNav
    %ul.navbar-nav
      %li.navbar-item
        = link_to 'All appointments', appointments_path, class: "nav-link"
  = link_to 'New appointment', new_appointment_path, class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, user-scalable=no", :name => "viewport"}/
    %title ActiverecordProject
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    .container-fluid
      = yield